// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.edu.ustc.center;

public final class ApiProtos {
  private ApiProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code center.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FILE_DOWNLOAD = 0;</code>
     */
    FILE_DOWNLOAD(0),
    /**
     * <pre>
     * Request with the hash of file(payload[0]) and download location(path of local filesystem)(payload[1])
     * Response, OK means download complete, ERROR means error message(string) in payload
     * </pre>
     *
     * <code>INDEX_DOWNLOAD = 1;</code>
     */
    INDEX_DOWNLOAD(1),
    /**
     * <pre>
     * Resuest with the hash of index
     * Response, OK means index content stored in payload, ERROR is same as above
     * </pre>
     *
     * <code>FILE_UPLOAD = 2;</code>
     */
    FILE_UPLOAD(2),
    /**
     * <pre>
     * Request with the path of the file to upload
     * Response, OK means upload complete, FAST_FORWARD means don't need upload, file hash in payload[0]. ERROR is same as above
     * </pre>
     *
     * <code>INDEX_UPLOAD = 3;</code>
     */
    INDEX_UPLOAD(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FILE_DOWNLOAD = 0;</code>
     */
    public static final int FILE_DOWNLOAD_VALUE = 0;
    /**
     * <pre>
     * Request with the hash of file(payload[0]) and download location(path of local filesystem)(payload[1])
     * Response, OK means download complete, ERROR means error message(string) in payload
     * </pre>
     *
     * <code>INDEX_DOWNLOAD = 1;</code>
     */
    public static final int INDEX_DOWNLOAD_VALUE = 1;
    /**
     * <pre>
     * Resuest with the hash of index
     * Response, OK means index content stored in payload, ERROR is same as above
     * </pre>
     *
     * <code>FILE_UPLOAD = 2;</code>
     */
    public static final int FILE_UPLOAD_VALUE = 2;
    /**
     * <pre>
     * Request with the path of the file to upload
     * Response, OK means upload complete, FAST_FORWARD means don't need upload, file hash in payload[0]. ERROR is same as above
     * </pre>
     *
     * <code>INDEX_UPLOAD = 3;</code>
     */
    public static final int INDEX_UPLOAD_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return FILE_DOWNLOAD;
        case 1: return INDEX_DOWNLOAD;
        case 2: return FILE_UPLOAD;
        case 3: return INDEX_UPLOAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.edu.ustc.center.ApiProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:center.Type)
  }

  /**
   * Protobuf enum {@code center.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <pre>
     * Already have the same hash
     * </pre>
     *
     * <code>FAST_FORWARD = 1;</code>
     */
    FAST_FORWARD(1),
    /**
     * <pre>
     * error message in payload
     * </pre>
     *
     * <code>ERROR = 2;</code>
     */
    ERROR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <pre>
     * Already have the same hash
     * </pre>
     *
     * <code>FAST_FORWARD = 1;</code>
     */
    public static final int FAST_FORWARD_VALUE = 1;
    /**
     * <pre>
     * error message in payload
     * </pre>
     *
     * <code>ERROR = 2;</code>
     */
    public static final int ERROR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    public static Result forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return FAST_FORWARD;
        case 2: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.edu.ustc.center.ApiProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:center.Result)
  }

  public interface FS_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:center.FS_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .center.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .center.Type type = 1;</code>
     */
    cn.edu.ustc.center.ApiProtos.Type getType();

    /**
     * <code>repeated bytes payload = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPayloadList();
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    int getPayloadCount();
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload(int index);
  }
  /**
   * Protobuf type {@code center.FS_Request}
   */
  public  static final class FS_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:center.FS_Request)
      FS_RequestOrBuilder {
    // Use FS_Request.newBuilder() to construct.
    private FS_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FS_Request() {
      type_ = 0;
      payload_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FS_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              payload_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.ustc.center.ApiProtos.FS_Request.class, cn.edu.ustc.center.ApiProtos.FS_Request.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .center.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .center.Type type = 1;</code>
     */
    public cn.edu.ustc.center.ApiProtos.Type getType() {
      cn.edu.ustc.center.ApiProtos.Type result = cn.edu.ustc.center.ApiProtos.Type.forNumber(type_);
      return result == null ? cn.edu.ustc.center.ApiProtos.Type.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> payload_;
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPayloadList() {
      return payload_;
    }
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload(int index) {
      return payload_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != cn.edu.ustc.center.ApiProtos.Type.FILE_DOWNLOAD.getNumber()) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < payload_.size(); i++) {
        output.writeBytes(2, payload_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != cn.edu.ustc.center.ApiProtos.Type.FILE_DOWNLOAD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < payload_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(payload_.get(i));
        }
        size += dataSize;
        size += 1 * getPayloadList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.ustc.center.ApiProtos.FS_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code center.FS_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:center.FS_Request)
        cn.edu.ustc.center.ApiProtos.FS_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.ustc.center.ApiProtos.FS_Request.class, cn.edu.ustc.center.ApiProtos.FS_Request.Builder.class);
      }

      // Construct using cn.edu.ustc.center.ApiProtos.FS_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Request_descriptor;
      }

      public cn.edu.ustc.center.ApiProtos.FS_Request getDefaultInstanceForType() {
        return cn.edu.ustc.center.ApiProtos.FS_Request.getDefaultInstance();
      }

      public cn.edu.ustc.center.ApiProtos.FS_Request build() {
        cn.edu.ustc.center.ApiProtos.FS_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.ustc.center.ApiProtos.FS_Request buildPartial() {
        cn.edu.ustc.center.ApiProtos.FS_Request result = new cn.edu.ustc.center.ApiProtos.FS_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.ustc.center.ApiProtos.FS_Request) {
          return mergeFrom((cn.edu.ustc.center.ApiProtos.FS_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.ustc.center.ApiProtos.FS_Request other) {
        if (other == cn.edu.ustc.center.ApiProtos.FS_Request.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.ustc.center.ApiProtos.FS_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.ustc.center.ApiProtos.FS_Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public cn.edu.ustc.center.ApiProtos.Type getType() {
        cn.edu.ustc.center.ApiProtos.Type result = cn.edu.ustc.center.ApiProtos.Type.forNumber(type_);
        return result == null ? cn.edu.ustc.center.ApiProtos.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public Builder setType(cn.edu.ustc.center.ApiProtos.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> payload_ = java.util.Collections.emptyList();
      private void ensurePayloadIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payload_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPayloadList() {
        return java.util.Collections.unmodifiableList(payload_);
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public int getPayloadCount() {
        return payload_.size();
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload(int index) {
        return payload_.get(index);
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder setPayload(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder addPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder addAllPayload(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePayloadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payload_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:center.FS_Request)
    }

    // @@protoc_insertion_point(class_scope:center.FS_Request)
    private static final cn.edu.ustc.center.ApiProtos.FS_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.ustc.center.ApiProtos.FS_Request();
    }

    public static cn.edu.ustc.center.ApiProtos.FS_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FS_Request>
        PARSER = new com.google.protobuf.AbstractParser<FS_Request>() {
      public FS_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FS_Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FS_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FS_Request> getParserForType() {
      return PARSER;
    }

    public cn.edu.ustc.center.ApiProtos.FS_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FS_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:center.FS_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .center.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .center.Type type = 1;</code>
     */
    cn.edu.ustc.center.ApiProtos.Type getType();

    /**
     * <code>optional .center.Result result = 2;</code>
     */
    int getResultValue();
    /**
     * <code>optional .center.Result result = 2;</code>
     */
    cn.edu.ustc.center.ApiProtos.Result getResult();

    /**
     * <code>repeated bytes payload = 3;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPayloadList();
    /**
     * <code>repeated bytes payload = 3;</code>
     */
    int getPayloadCount();
    /**
     * <code>repeated bytes payload = 3;</code>
     */
    com.google.protobuf.ByteString getPayload(int index);
  }
  /**
   * Protobuf type {@code center.FS_Response}
   */
  public  static final class FS_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:center.FS_Response)
      FS_ResponseOrBuilder {
    // Use FS_Response.newBuilder() to construct.
    private FS_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FS_Response() {
      type_ = 0;
      result_ = 0;
      payload_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FS_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              payload_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.ustc.center.ApiProtos.FS_Response.class, cn.edu.ustc.center.ApiProtos.FS_Response.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .center.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .center.Type type = 1;</code>
     */
    public cn.edu.ustc.center.ApiProtos.Type getType() {
      cn.edu.ustc.center.ApiProtos.Type result = cn.edu.ustc.center.ApiProtos.Type.forNumber(type_);
      return result == null ? cn.edu.ustc.center.ApiProtos.Type.UNRECOGNIZED : result;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>optional .center.Result result = 2;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>optional .center.Result result = 2;</code>
     */
    public cn.edu.ustc.center.ApiProtos.Result getResult() {
      cn.edu.ustc.center.ApiProtos.Result result = cn.edu.ustc.center.ApiProtos.Result.forNumber(result_);
      return result == null ? cn.edu.ustc.center.ApiProtos.Result.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> payload_;
    /**
     * <code>repeated bytes payload = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPayloadList() {
      return payload_;
    }
    /**
     * <code>repeated bytes payload = 3;</code>
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload(int index) {
      return payload_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != cn.edu.ustc.center.ApiProtos.Type.FILE_DOWNLOAD.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (result_ != cn.edu.ustc.center.ApiProtos.Result.OK.getNumber()) {
        output.writeEnum(2, result_);
      }
      for (int i = 0; i < payload_.size(); i++) {
        output.writeBytes(3, payload_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != cn.edu.ustc.center.ApiProtos.Type.FILE_DOWNLOAD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (result_ != cn.edu.ustc.center.ApiProtos.Result.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, result_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < payload_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(payload_.get(i));
        }
        size += dataSize;
        size += 1 * getPayloadList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.FS_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.ustc.center.ApiProtos.FS_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code center.FS_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:center.FS_Response)
        cn.edu.ustc.center.ApiProtos.FS_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.ustc.center.ApiProtos.FS_Response.class, cn.edu.ustc.center.ApiProtos.FS_Response.Builder.class);
      }

      // Construct using cn.edu.ustc.center.ApiProtos.FS_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        result_ = 0;

        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_FS_Response_descriptor;
      }

      public cn.edu.ustc.center.ApiProtos.FS_Response getDefaultInstanceForType() {
        return cn.edu.ustc.center.ApiProtos.FS_Response.getDefaultInstance();
      }

      public cn.edu.ustc.center.ApiProtos.FS_Response build() {
        cn.edu.ustc.center.ApiProtos.FS_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.ustc.center.ApiProtos.FS_Response buildPartial() {
        cn.edu.ustc.center.ApiProtos.FS_Response result = new cn.edu.ustc.center.ApiProtos.FS_Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.result_ = result_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.ustc.center.ApiProtos.FS_Response) {
          return mergeFrom((cn.edu.ustc.center.ApiProtos.FS_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.ustc.center.ApiProtos.FS_Response other) {
        if (other == cn.edu.ustc.center.ApiProtos.FS_Response.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.ustc.center.ApiProtos.FS_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.ustc.center.ApiProtos.FS_Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public cn.edu.ustc.center.ApiProtos.Type getType() {
        cn.edu.ustc.center.ApiProtos.Type result = cn.edu.ustc.center.ApiProtos.Type.forNumber(type_);
        return result == null ? cn.edu.ustc.center.ApiProtos.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public Builder setType(cn.edu.ustc.center.ApiProtos.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .center.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int result_ = 0;
      /**
       * <code>optional .center.Result result = 2;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <code>optional .center.Result result = 2;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .center.Result result = 2;</code>
       */
      public cn.edu.ustc.center.ApiProtos.Result getResult() {
        cn.edu.ustc.center.ApiProtos.Result result = cn.edu.ustc.center.ApiProtos.Result.forNumber(result_);
        return result == null ? cn.edu.ustc.center.ApiProtos.Result.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .center.Result result = 2;</code>
       */
      public Builder setResult(cn.edu.ustc.center.ApiProtos.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .center.Result result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> payload_ = java.util.Collections.emptyList();
      private void ensurePayloadIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payload_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPayloadList() {
        return java.util.Collections.unmodifiableList(payload_);
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public int getPayloadCount() {
        return payload_.size();
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public com.google.protobuf.ByteString getPayload(int index) {
        return payload_.get(index);
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public Builder setPayload(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public Builder addPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public Builder addAllPayload(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePayloadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payload_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 3;</code>
       */
      public Builder clearPayload() {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:center.FS_Response)
    }

    // @@protoc_insertion_point(class_scope:center.FS_Response)
    private static final cn.edu.ustc.center.ApiProtos.FS_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.ustc.center.ApiProtos.FS_Response();
    }

    public static cn.edu.ustc.center.ApiProtos.FS_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FS_Response>
        PARSER = new com.google.protobuf.AbstractParser<FS_Response>() {
      public FS_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FS_Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FS_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FS_Response> getParserForType() {
      return PARSER;
    }

    public cn.edu.ustc.center.ApiProtos.FS_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BC_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:center.BC_Request)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code center.BC_Request}
   */
  public  static final class BC_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:center.BC_Request)
      BC_RequestOrBuilder {
    // Use BC_Request.newBuilder() to construct.
    private BC_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BC_Request() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BC_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.ustc.center.ApiProtos.BC_Request.class, cn.edu.ustc.center.ApiProtos.BC_Request.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.ustc.center.ApiProtos.BC_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code center.BC_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:center.BC_Request)
        cn.edu.ustc.center.ApiProtos.BC_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.ustc.center.ApiProtos.BC_Request.class, cn.edu.ustc.center.ApiProtos.BC_Request.Builder.class);
      }

      // Construct using cn.edu.ustc.center.ApiProtos.BC_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Request_descriptor;
      }

      public cn.edu.ustc.center.ApiProtos.BC_Request getDefaultInstanceForType() {
        return cn.edu.ustc.center.ApiProtos.BC_Request.getDefaultInstance();
      }

      public cn.edu.ustc.center.ApiProtos.BC_Request build() {
        cn.edu.ustc.center.ApiProtos.BC_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.ustc.center.ApiProtos.BC_Request buildPartial() {
        cn.edu.ustc.center.ApiProtos.BC_Request result = new cn.edu.ustc.center.ApiProtos.BC_Request(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.ustc.center.ApiProtos.BC_Request) {
          return mergeFrom((cn.edu.ustc.center.ApiProtos.BC_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.ustc.center.ApiProtos.BC_Request other) {
        if (other == cn.edu.ustc.center.ApiProtos.BC_Request.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.ustc.center.ApiProtos.BC_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.ustc.center.ApiProtos.BC_Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:center.BC_Request)
    }

    // @@protoc_insertion_point(class_scope:center.BC_Request)
    private static final cn.edu.ustc.center.ApiProtos.BC_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.ustc.center.ApiProtos.BC_Request();
    }

    public static cn.edu.ustc.center.ApiProtos.BC_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BC_Request>
        PARSER = new com.google.protobuf.AbstractParser<BC_Request>() {
      public BC_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BC_Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BC_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BC_Request> getParserForType() {
      return PARSER;
    }

    public cn.edu.ustc.center.ApiProtos.BC_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BC_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:center.BC_Response)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code center.BC_Response}
   */
  public  static final class BC_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:center.BC_Response)
      BC_ResponseOrBuilder {
    // Use BC_Response.newBuilder() to construct.
    private BC_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BC_Response() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BC_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.ustc.center.ApiProtos.BC_Response.class, cn.edu.ustc.center.ApiProtos.BC_Response.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.ApiProtos.BC_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.ustc.center.ApiProtos.BC_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code center.BC_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:center.BC_Response)
        cn.edu.ustc.center.ApiProtos.BC_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.ustc.center.ApiProtos.BC_Response.class, cn.edu.ustc.center.ApiProtos.BC_Response.Builder.class);
      }

      // Construct using cn.edu.ustc.center.ApiProtos.BC_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.ustc.center.ApiProtos.internal_static_center_BC_Response_descriptor;
      }

      public cn.edu.ustc.center.ApiProtos.BC_Response getDefaultInstanceForType() {
        return cn.edu.ustc.center.ApiProtos.BC_Response.getDefaultInstance();
      }

      public cn.edu.ustc.center.ApiProtos.BC_Response build() {
        cn.edu.ustc.center.ApiProtos.BC_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.ustc.center.ApiProtos.BC_Response buildPartial() {
        cn.edu.ustc.center.ApiProtos.BC_Response result = new cn.edu.ustc.center.ApiProtos.BC_Response(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.ustc.center.ApiProtos.BC_Response) {
          return mergeFrom((cn.edu.ustc.center.ApiProtos.BC_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.ustc.center.ApiProtos.BC_Response other) {
        if (other == cn.edu.ustc.center.ApiProtos.BC_Response.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.ustc.center.ApiProtos.BC_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.ustc.center.ApiProtos.BC_Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:center.BC_Response)
    }

    // @@protoc_insertion_point(class_scope:center.BC_Response)
    private static final cn.edu.ustc.center.ApiProtos.BC_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.ustc.center.ApiProtos.BC_Response();
    }

    public static cn.edu.ustc.center.ApiProtos.BC_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BC_Response>
        PARSER = new com.google.protobuf.AbstractParser<BC_Response>() {
      public BC_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BC_Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BC_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BC_Response> getParserForType() {
      return PARSER;
    }

    public cn.edu.ustc.center.ApiProtos.BC_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_center_FS_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_center_FS_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_center_FS_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_center_FS_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_center_BC_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_center_BC_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_center_BC_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_center_BC_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\006center\"9\n\nFS_Request\022\032\n\004typ" +
      "e\030\001 \001(\0162\014.center.Type\022\017\n\007payload\030\002 \003(\014\"Z" +
      "\n\013FS_Response\022\032\n\004type\030\001 \001(\0162\014.center.Typ" +
      "e\022\036\n\006result\030\002 \001(\0162\016.center.Result\022\017\n\007pay" +
      "load\030\003 \003(\014\"\014\n\nBC_Request\"\r\n\013BC_Response*" +
      "P\n\004Type\022\021\n\rFILE_DOWNLOAD\020\000\022\022\n\016INDEX_DOWN" +
      "LOAD\020\001\022\017\n\013FILE_UPLOAD\020\002\022\020\n\014INDEX_UPLOAD\020" +
      "\003*-\n\006Result\022\006\n\002OK\020\000\022\020\n\014FAST_FORWARD\020\001\022\t\n" +
      "\005ERROR\020\0022A\n\tFSService\0224\n\007FSServe\022\022.cente" +
      "r.FS_Request\032\023.center.FS_Response\"\000B\037\n\022c",
      "n.edu.ustc.centerB\tApiProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_center_FS_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_center_FS_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_center_FS_Request_descriptor,
        new java.lang.String[] { "Type", "Payload", });
    internal_static_center_FS_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_center_FS_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_center_FS_Response_descriptor,
        new java.lang.String[] { "Type", "Result", "Payload", });
    internal_static_center_BC_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_center_BC_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_center_BC_Request_descriptor,
        new java.lang.String[] { });
    internal_static_center_BC_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_center_BC_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_center_BC_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
